# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: TeamCity connector test

on:
  pull_request:
    branches:
      - master

permissions:
  checks: write
  contents: read
  issues: read
  pull-requests: write

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Gradle
      run: gradle test

    - name: Publish Test Report
      uses: starburstdata/action-testng-report@v1.0.0
      with:
        report_paths: 'test-report/xml/testng-results.xml'
        show_skipped: true
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload event file
      uses: actions/upload-artifact@v2
      with:
        name: event_file
        path: ${{ github.event_path }}

    - name: Upload Testerra results
      uses: actions/upload-artifact@v2
      with:
        name: 'testerra_results'
        path: test-report/

    # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
    # the publishing section of your build.gradle
#     - name: Publish to GitHub Packages
#       run: gradle publish
#       env:
#         USERNAME: ${{ github.actor }}
#         TOKEN: ${{ secrets.GITHUB_TOKEN }}
